<a href="https://colab.research.google.com/github/Harin22/5-python-projects/blob/master/Basic_Tensorflow_operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print(x)

print(x.shape)

print(x.dtype)

print(x + x)
print(5 * x)
print(tf.concat([x, x, x], axis=0))

print(tf.nn.softmax(x, axis=-1))

print(tf.reduce_sum(x))
print(tf.convert_to_tensor([1, 2, 3]))
print(tf.reduce_sum([1, 2, 3]))

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(6, 3), dtype=float32)
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)
tf.Tensor(21.0, shape=(), dtype=float32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
