<a href="https://colab.research.google.com/github/Harin22/5-python-projects/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [ ]:
arr1 = np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [ ]:
arr1 = np.ones(5)
print(arr1)

[1. 1. 1. 1. 1.]


In [ ]:
ar2 = np.empty(5)
print(ar2)

[0. 0. 0. 0. 0.]


In [ ]:
ar3 = np.arange(5)
for i in ar3:
  print(ar3)

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [ ]:
ar4 = np.linspace(0, 5, num=5)
print(ar4)

[0.   1.25 2.5  3.75 5.  ]


# 2nd Augest

In [ ]:
kk = np.array([[1, 3], [5, 6]])
print(kk)

[[1 3]
 [5 6]]


In [ ]:
import numpy as np

k = np.random.seed(8)
print(k)


None


In [ ]:
i = np.random.choice([3, 5, 7, 9])
print(i)

j = np.random.choice([1,23,4,5,6,7], size=(3, 5))
print(j)

3
[[23 23  7  4  1]
 [ 5  1  1  7  7]
 [ 6 23  5  4  5]]


In [ ]:
h = np.arange(18)
print(h)

i = np.reshape(h,(9,2)) # the reshape array should be (both array multiple )
print(i)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]


In [ ]:
k = np.arange(10)
print(k)

i = np.reshape(k,(2,5))
print(i)

j = np.ravel(i)  #np.ravel function in NumPy is used to flatten an array into a 1D array. It returns a contiguous flattened array
print(j)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
i = np.array([[1,2,3],[4,5,6]])
print(i)

j = np.transpose(i)
print(j)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[7,8,9],[10,11,12]])

k = np.concatenate((i,j),axis=0)
print(k)

#Axis 0: Refers to rows in a 2D array. Concatenating along axis=0 stacks arrays on top of each other, increasing the number of rows.
#Axis 1: Refers to columns in a 2D array. Concatenating along axis=1 places arrays side-by-side, increasing the number of columns.

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 7 augest

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7,8,9])

stack = np.stack((a, b,c), axis=0)
print(stack)

stack = np.stack((a, b), axis=1)
print(stack)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.array([[1, 2, 3], [7,34,53]])
b = np.array([[4, 5, 6], [7,30,53]])
c = np.array([7,8,9,])

hstack = np.hstack((a, b,)) # bring all in straight line
print(hstack)

vstack = np.vstack((a, b,c))
print(vstack)

[[ 1  2  3  4  5  6]
 [ 7 34 53  7 30 53]]
[[ 1  2  3]
 [ 7 34 53]
 [ 4  5  6]
 [ 7 30 53]
 [ 7  8  9]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dstack = np.dstack((a,b))
print("dstack is ", dstack)  #np.dstack is used to combine multiple 2D arrays (channels) into a single 3D array. This is crucial in image processing where each image has multiple channels (like RGB).

dstack is  [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


# 11 sept

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6,8,9])
print(arr)

splite = np.split(arr, 2)
print(splite)

re = np.reshape(arr,(2,4))
print("resha;p" , re)

for i in splite:
  print(i)

[1 2 3 4 5 6 8 9]
[array([1, 2, 3, 4]), array([5, 6, 8, 9])]
resha;p [[1 2 3 4]
 [5 6 8 9]]
[1 2 3 4]
[5 6 8 9]


In [15]:
array = np.arange(12).reshape(3, 4)

sub_arrays = np.array_split(array, 2)
print(sub_arrays)

for i in sub_arrays:
    print(i)

[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]


In [20]:
i = np.arange(24).reshape(6, 2, 2)
sub_arrays = np.dsplit(i, 2)
print(sub_arrays)


[array([[[ 0],
        [ 2]],

       [[ 4],
        [ 6]],

       [[ 8],
        [10]],

       [[12],
        [14]],

       [[16],
        [18]],

       [[20],
        [22]]]), array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]],

       [[21],
        [23]]])]


In [22]:
array = np.array([0, 2, 0, 4, 5])

nonzero_indices = np.nonzero(array)
print(nonzero_indices)

for i in nonzero_indices:
  print(i)

(array([1, 3, 4]),)
[1 3 4]


In [24]:
array = np.array([10, 15, 20, 25, 30])

indices = np.where(array > 20)
print(indices)

for i in indices:
  print(i)

selected_elements = np.where(array > 20, array, -1)
print(selected_elements)


(array([3, 4]),)
[3 4]
