<a href="https://colab.research.google.com/github/Harin22/5-python-projects/blob/master/numpy%20pract%20for%20ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [9]:
i = 8

for j in range(10):
    k = (j * i )
    print(k * 8)


0
64
128
192
256
320
384
448
512
576


In [15]:
zeros = np.zeros((10, 10)), np.ones((5,5))
print(zeros , ", ")

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])) , 


In [16]:
arange = np.arange(10)
print(arange)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
i = np.arange(20).reshape(2,10)
print(i)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [33]:
j = np.linspace(0, 40).reshape(5,10)
print(j)

[[ 0.          0.81632653  1.63265306  2.44897959  3.26530612  4.08163265
   4.89795918  5.71428571  6.53061224  7.34693878]
 [ 8.16326531  8.97959184  9.79591837 10.6122449  11.42857143 12.24489796
  13.06122449 13.87755102 14.69387755 15.51020408]
 [16.32653061 17.14285714 17.95918367 18.7755102  19.59183673 20.40816327
  21.2244898  22.04081633 22.85714286 23.67346939]
 [24.48979592 25.30612245 26.12244898 26.93877551 27.75510204 28.57142857
  29.3877551  30.20408163 31.02040816 31.83673469]
 [32.65306122 33.46938776 34.28571429 35.10204082 35.91836735 36.73469388
  37.55102041 38.36734694 39.18367347 40.        ]]


In [36]:
data_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

k = np.transpose(data_2d)
print("in 3d:", k)

print(data_2d)

in 3d: [[10 40 70]
 [20 50 80]
 [30 60 90]]
[[10, 20, 30], [40, 50, 60], [70, 80, 90]]


In [40]:
data_2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90], [40, 50, 60], [70, 80, 90]]

k = np.transpose(data_2d)
display = np.array(k)
print("this is a 3d array")
print(display)

this is a 3d array
[[10 40 70 40 70]
 [20 50 80 50 80]
 [30 60 90 60 90]]


In [48]:
import numpy as np

data = [10, 12, 23, 23, 16, 23, 21, 16]
std_dev = np.std(data)
print(std_dev)

4.898979485566356


In [55]:
import numpy as np

matrix1 = [[10, 20, 30], [40, 50, 60]]
matrix2 = [[1, 2], [3, 4], [5, 6]]

dotmat = np.dot(matrix1)
print(dotmat)

TypeError: dot() missing 1 required positional argument: 'b'

In [59]:
la = np.split(matrix1)
print(la)

TypeError: split() missing 1 required positional argument: 'indices_or_sections'

In [5]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[1, 2], [3, 4]])

display(arr1)
display(arr2)

array([1, 2, 3, 4])

array([[1, 2],
       [3, 4]])

In [12]:
zeros_array = np.zeros((3, 3))   # 3x3 matrix filled with zeros
ones_array = np.full((2, 2), 1)  # 2x2 matrix filled with ones
random_array = np.random.randint(4, 4)  # 4x4 matrix filled with random values

print(random_array)

print(zeros_array)

ValueError: low >= high

In [15]:
identity_matrix = np.eye(5)  # 3x3 identity matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
random1 = np.random.rand(1, 20, 2)
random = random1.reshape(20, 2)
random_number = np.random.uniform(0, 9, (3,3))

print(random_number)


print(random)

[[0.75761347 0.39849035 5.88264073]
 [5.3033106  6.42787809 6.98493656]
 [8.52182291 8.79580919 0.57560259]]
[[0.62413531 0.70014666]
 [0.92007176 0.27544134]
 [0.4749805  0.47013935]
 [0.28621516 0.47767283]
 [0.84245463 0.75740002]
 [0.76968224 0.69634938]
 [0.79357097 0.05721743]
 [0.8803666  0.49532471]
 [0.36087439 0.45747386]
 [0.4540465  0.43758683]
 [0.58945373 0.53488746]
 [0.94162223 0.40662952]
 [0.77663493 0.65542968]
 [0.41697562 0.26380761]
 [0.12591506 0.44384149]
 [0.08678296 0.76722509]
 [0.58692488 0.37186757]
 [0.26962786 0.6864599 ]
 [0.20772589 0.04185558]
 [0.51525521 0.78736282]]


In [28]:
array2 = np.full((3, 8))
array1 = np.ones((3, 3))

value = np.subtract(array2, array1)


print(array2)
print(array1)
print(value)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
i = np.array([[1, 2, 3], [4, 5, 6]])

rs = i.reshape(2,3)
print(rs)

[[1 2 3]
 [4 5 6]]


In [40]:
c = ([[1, 2, 3], [4, 5, 6]])
d = ([[7, 8, 9, 4,10, 11, 12, 5]])

argsorted_array = np.sort(d)  # Indices of sorted elements
print(argsorted_array)

vstack = np.hstack(( d))
#print(vstack)


[[ 4  5  7  8  9 10 11 12]]


In [37]:
split_array = np.split(c, [2])
print(split_array)

[array([[1, 2, 3],
       [4, 5, 6]]), array([], shape=(0, 3), dtype=int64)]


In [46]:
data = np.array([[5, 2, 9],
                 [1, 7, 3],
                 [4, 8, 6]])

# Calculate the mean of each row
means = np.mean(data, axis=1)
sort = np.argsort(means)
rowsort = np.sort(data)
max_index = np.argmax(data)
min_index = np.argmin(data)

print(max_index)
print(min_index)


print(sort)
#print(means, axis = 1)
print(rowsort)

2
3
[1 0 2]
[[2 5 9]
 [1 3 7]
 [4 6 8]]


In [52]:
dot_product = np.dot(data, data)
print(dot_product)

matrix_inv = np.linalg.inv(data)
print(matrix_inv)

la = np.linalg.

[[ 63  96 105]
 [ 24  75  48]
 [ 52 112  96]]
[[-0.23076923 -0.76923077  0.73076923]
 [-0.07692308  0.07692308  0.07692308]
 [ 0.25641026  0.41025641 -0.42307692]]


In [53]:
eigenvalues, eigenvectors = np.linalg.eig(data)
print(eigenvalues)
print(eigenvectors)


[14.5347587  -1.16020158  4.62544289]
[[ 0.68122661  0.80792532  0.88812997]
 [ 0.34705395  0.11357376 -0.45509057]
 [ 0.64458038 -0.5782367   0.06416953]]


In [51]:
import numpy as np

np.random.seed(42)  # Set the seed to 42
random_numbers1 = np.random.rand(3)  # Generate 3 random numbers
print("First set of random numbers:", random_numbers1)

np.random.seed(42)  # Set the seed to 42 again
random_numbers2 = np.random.rand(3)  # Generate 3 random numbers again
print("Second set of random numbers:", random_numbers2)

First set of random numbers: [0.37454012 0.95071431 0.73199394]
Second set of random numbers: [0.37454012 0.95071431 0.73199394]
